import { Head, Html, Main, NextScript } from "next/document";

export default function Document() {
    return (
        <Html lang="en">
            <Head>
                <title>Ersa Khorsandi Portfolio</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/logo.jpg" />
                <link href="https://fonts.cdnfonts.com/css/satoshi" rel="stylesheet" />
            </Head>
            <body style={{ padding: 0, margin: 0 }}>
                <Main />
                <NextScript />
            </body>
        </Html>
    );
}
